### ISSUE TITLE
그거 틀림 ㅋㅋㄹㅃㅃ

### ISSUE THREAD

**Issue by lhwdev2008** [lee-jongwoo/lee-jongwoo#1]
## 규칙
1. Use Korean(한국어 사랑❤️).
2. Use Android Studio on Windows.
3. Use Jetpack Compose whenever possible.
4. Use Manager Classes to reduce boilerplate code.
5. Use [ktLint](https://github.com/pinterest/ktlint) to clean up your code.

**Comment by lee-jongwoo** [comment]
대체 누가 윈도우 씀?
macOS > Ubuntu > Debian > Windows
